### ISSUE TITLE
Official Minecraft VR does not have Linkless Quest Support

### ISSUE THREAD

**Issue by JadianRadiator** [Sorenon/MCXR#14]
Official Minecraft VR does not have Linkless Quest Support.
You *have* to use Oculus Link (or some other pcvr emulator) to run Official Minecraft VR.

**Comment by CADIndie** [comment]
Hi, im from QuestCraf. We are currently working on other aspects and MCXR will be adding the feature set sometime in the future to bind with QuestCraft.

**Comment by JadianRadiator** [comment]
Okay, so what's the current website?
Because the only one I've found is [https://quest-craft.com/](https://quest-craft.com/), which is down/dead

**Comment by CADIndie** [comment]
The website is down at request of developers and intrest of community staff. All QuestCraft updates are handled at both our community server (https://discord.gg/ppWG7DyJ) and our dev server (https://discord.gg/VAE9thBS).
