### ISSUE TITLE
HP Reverb G2 not working

### ISSUE THREAD

**Issue by UWUplus** [Sorenon/MCXR#17]
I tried playing on a HP Reverb G2. 

Sadly the controls don't seem to react in any way, neither does punching blocks do anything.

Is this a known issue?

**Comment by technobaboo** [comment]
sounds like we just never made an interaction profile for it

**Comment by UWUplus** [comment]
There seems to be an interaction profile in SteamVR with the bindings, but the game doesn't react to it, if you want me to send any data, I'd be more than happy to do so.

**Comment by Sorenon** [comment]
i had explicit g2 support on the low priority todo list since i just assumed steamvr would provide compatibility bindings from the wmr / oculus touch bindings

as it seems like it doesn't do that i'll start working on support asap
