### ISSUE TITLE
Crashing with Medieval Modpack

### ISSUE THREAD

**Issue by gbreuil** [Sorenon/MCXR#19]
I use curseforge, with a fast created modpack no issue without contents mods, i use only fabric + sodium + iris + complementary shaders and it works (not big fps with shaders). Had to set SteamVR to use OpenXR.
When i launch a save or create new one i have a crash on the modpack, i had no problem with it for now and it's up to date 1.18.1 as far as i know.
Maybe a conflicting mod somewhere in it but i don't know where to start (200 mods).

`---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 12/21/21, 12:13 AM
Description: Unexpected error

java.lang.NoSuchFieldError: BASE
	at net.sorenon.mcxr.core.MCXRScale.getScale(MCXRScale.java:16)
	at net.sorenon.mcxr.play.MCXRPlayClient.getCameraScale(MCXRPlayClient.java:117)
	at net.sorenon.mcxr.play.MCXRPlayClient.getCameraScale(MCXRPlayClient.java:109)
	at net.sorenon.mcxr.play.openxr.XrRenderer.renderLayerOpenXR(XrRenderer.java:144)
	at net.sorenon.mcxr.play.openxr.XrRenderer.renderFrame(XrRenderer.java:97)
	at net.sorenon.mcxr.play.openxr.OpenXR.loop(OpenXR.java:154)
	at net.minecraft.class_310.redirect$eng000$loop(class_310.java:21126)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.sorenon.mcxr.core.MCXRScale.getScale(MCXRScale.java:16)
	at net.sorenon.mcxr.play.MCXRPlayClient.getCameraScale(MCXRPlayClient.java:117)
	at net.sorenon.mcxr.play.MCXRPlayClient.getCameraScale(MCXRPlayClient.java:109)
	at net.sorenon.mcxr.play.openxr.XrRenderer.renderLayerOpenXR(XrRenderer.java:144)
	at net.sorenon.mcxr.play.openxr.XrRenderer.renderFrame(XrRenderer.java:97)

-- Affected level --
Details:
	All players: 1 total; [class_746['Silver_Clock'/71, l='ClientLevel', x=3182.15, y=78.00, z=-470.59]]
	Chunk stats: 1024, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (960,384,16), Section: (at 0,0,0 in 60,24,1; chunk contains blocks 960,-64,16 to 975,319,31), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,-64,0 to 1023,319,511)
	Level time: 30782 game time, 9422 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Terralith_2.0_Biome_Name_Fix.zip, Skyrim Soundpack v5.8.zip, STONEBORN - 1.18 - V3.0.zip, Excalibur_V1.18.zip, EmbellishedStone-1.18-1.0.0.zip, EclecticTrove-1.18-1.0.1.zip

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1627052160 bytes (1551 MiB) / 5637144576 bytes (5376 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon RX 6700 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x73df
	Graphics card #0 versionInfo: DriverVersion=30.0.14011.3017
	Graphics card #1 name: Virtual Display Adapter
	Graphics card #1 vendor: Microsoft
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: unknown
	Graphics card #1 versionInfo: DriverVersion=10.0.19041.1
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.73
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.73
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 40881.71
	Virtual memory used (MB): 25041.90
	Swap memory total (MB): 24576.00
	Swap memory used (MB): 428.31
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8192m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 3.0.1
		additionalbars: Additional Bars 2.2.1
		adorn: Adorn 3.0.0+1.18.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advancementplaques: Advancement Plaques 1.4.3
		advancements-enlarger: Advancements Enlarger 0.2.4
		adventurez: AdventureZ 1.4.6
		alloy_forgery: Alloy Forgery 2.0.8+1.18
		amecsapi: Amecs API 1.3.2+mc1.18-pre1
		animal_feeding_trough: Animal Feeding Trough 1.0.2+1.18
		apoli: Apoli 2.2.2
		aqupdcaracal: Caracal mob 1.18-1.3.4
		aqupdgrizzly: Grizzly Bear mob 1.18-1.2.1
		arcanus: Arcanus 1.24
		architectury: Architectury 3.2.51
		backslot: BackSlot 1.2.3
		backslotaddon: BackSlot Addon 1.0.7
		balm-fabric: Balm 2.3.0+0
		bcc: BetterCompatibilityChecker fabric-1.0.4
		bclib: BCLib 1.1.3
		beehivetooltips: Beehive Tooltips 1.4.1
		beenfo: Beenfo 1.18-fabric0.43.1-1.3.3
		besmirchment: Besmirchment 1.18-3
		betterf3: BetterF3 1.2.2
		betterfpsdist: Better FPS distance Mod 1.18-1.3
		betternether: Better Nether 6.0.7
		bettersleeping: BetterSleeping 0.5.1+1.18
		betterthirdperson: Better Third Person 1.5.4
		bewitchment: Bewitchment 1.18-4
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.4.1
		boatcontainer: BoatContainer 1.0.4
		bobby: Bobby 3.1.0
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.3-1.18
		bountiful: Bountiful 2.0.1
		breakprogress: Break Progress 1.0.1
		calio: Calio 1.4.2
		campchair: Camp Chair 1.0.0
		capybara: Capybara 1.0.0
		cardinal-components-base: Cardinal Components API (base) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.0.1
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		cardinal-components-world: Cardinal Components API (worlds) 4.0.0
		carrier: Carrier 1.9.0
		chat_heads: Chat Heads 0.6.0
		cherishedworlds: Cherished Worlds 2.0.1-1.18
		cleancut: CleanCut 1.18-4.0-fabric
		clickadv: Clickable Advancements Mod 2.1
		clienttweaks: Client Tweaks 7.0.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		clumps: Clumps 8.0.3
		coat: Coat 1.0.0-beta.15
		collective-fabric: Collective (Fabric) 3.14
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		companion_bats: Companion Bats 1.18.7
		confabricate: confabricate 2.1.0-SNAPSHOT+4.1.1
		conjuring: Conjuring 1.0.17+1.18
		continuity: Continuity 1.0.3+1.18
		controlling: Controlling For Fabric 9.0.4
		cosmetic-armor: Cosmetic Armor 1.2.0
		cosmetica: Cosmetica 0.3.2
		craftpresence: CraftPresence 1.8.8
		crawl: Crawl 0.10.0
		crowdin-translate: CrowdinTranslate 1.4+1.18
		cspirit: Christmas Spirit 1.1.3-1.18
		dark-enchanting: Dark Enchanting 0.6.2+1.18
		deathlog: DeathLog 0.2.4+1.18
		deepslatecutting: Deepslate Cutting 1.3.0
		dehydration: Dehydration 1.2.5
		doubledoors-fabric: Double Doors (Fabric) 3.1
		dragonloot: DragonLoot 1.0.9
		drippyloadingscreen: Drippy Loading Screen 1.4.2
		dripstone_fluid_lib: Dripstone Fluid Lib 1.1.1
		dungeons_arise: When Dungeons Arise 2.1.49b-fabric
		dusk: Dusk Mod 1.18-1.7
		dynview: Dynamic View Mod 1.18-1.5
		earthtojavamobs: Earth2Java 1.7.4+1.18
		easymagic: Easy Magic 3.2.0
		effective: Effective 1.0
		eldritch_mobs: Eldritch Mobs 1.10.1
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		enchant_giver: Enchant Giver 1.1.0
		enchantedtooltips: Enchanted ToolTips 1.3.5-1.18
		enchantinginfuser: Enchanting Infuser 3.1.0
		enchantment_lore: Enchantment Lore 1.2.3+MC1.18-1.18.1
		enchdesc: EnchantmentDescriptions 9.0.3
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.2+1.18
		enhancedcelestials: Enhanced Celestials 2.0.6
		environmentz: EnvironmentZ 1.2.0
		equipmentcompare: Equipment Compare 1.2.9
		experiencebugfix: Experience Bug Fix 18
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd14
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33514
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9514
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabricloader: Fabric Loader 0.12.12
		fallingleaves: Falling Leaves 1.8.1+1.18.1
		fallingtree: FallingTree 2.16.1
		fancymenu: FancyMenu 2.4.3
		farmersdelight: Farmer's Delight 1.18.1-0.2.0
		fart: Fart 1.0.0
		ferritecore: FerriteCore 4.0.0
		fiber: fiber 0.23.0-2
		fireworkfrenzy: Firework Frenzy 1.7
		forgeconfigapiport: Forge Config API Port 3.1.0
		forgottenrecipes: ForgottenRecipes 1.18.1-1.0.0
		friendsandfoes: Friends&Foes 1.0.2
		gbfabrictools: GBfabrictools 1.3.4+1.18
		geckolib3: Geckolib 3.0.23
		geodes: More Geodes 1.2.0
		givemehats: Give Me Hats! 1.7.5
		go-fish: Go Fish 1.4.1-1.18.1
		goblintraders: Goblin Traders 1.4.1
		goosik-config: goosik-config 0.2.0
		graveyard: The Graveyard 1.1
		guild: Guild 0.3.6
		harvest_scythes: Harvest Scythes 2.3.2
		heartbond: Heartbond 1.2.0
		highlighter: Highlighter 1.1.2
		horseinfo: Horse Info 0.4.1-1.18
		horsestatsvanilla: Horse Stats Vanilla 4.1.10
		ibarnorigins: ibarn's origins addon 1.0.5
		icarus: Icarus 1.9
		iceberg: Iceberg 1.0.27
		illuminations: Illuminations 1.10.2
		impersonate: Impersonate 2.4.0
		indium: Indium 1.0.2-alpha1+mc1.18
		infusion_table: Infusion Table 1.0.5
		inmis: Inmis 2.4.0-1.18
		interactic: Interactic 0.1.7+1.18
		inventoryhud: Inventory HUD + 3.4.2
		inventorysorter: Inventory Sorter 1.8.1-1.18
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.1.3
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		just_end_anchor: Just An End Anchor 1.0.1
		kambrik: Kambrik 3.0.0
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kibe: Kibe 1.9.4-BETA+1.18
		kleeslabs: KleeSlabs 11.0.0
		konkrete: Konkrete 1.3.2
		krypton: Krypton 0.1.6
		kyrptconfig: Kyrpt Config 1.2.6-1.18
		lambdabettergrass: LambdaBetterGrass 1.2.1+1.17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lank: Lankasters Origins 1.0.0
		lavajava: Lava Java 0.2.0
		lazydfu: LazyDFU 0.1.2
		legendarytooltips: Legendary Tooltips 1.1.5
		levelz: LevelZ 1.1.3
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 5.1.0+1.18
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.3.0+1.17.1
		lithium: Lithium 0.7.6
		lovely_snails: Lovely Snails 1.0.3+1.18
		maelstrom_library: Maelstrom Library 1.2.3-1.18-rc3
		mavm: More Axolotl Variants Mod 1.0.6
		maybe-more-data: Maybe More Data 1.0.0-1.18
		mcda: MC Dungeons Armors 1.8.4
		mcdw: MC Dungeons Weapons 3.6.0-1.18
		mcf-reap: MaxVar reap for fabric 1.7.0
		mcxr-core: [MCXR] Core 0.1.0
		mcxr-play: [MCXR] Play 0.1.1
		medievalorigins: Medieval Origins 3.1.0
		medievalweapons: Medieval Weapons 1.1.7
		medivalmusic: Medival Music Mod 1.18-1.2
		megane: megane 6.1.2
		megane-base: megane-base 6.1.2
		megane-fabric-transfer: megane-fabric-transfer 6.1.2+1.5.4-b4f4f6cda9
		megane-kibe: megane-kibe 6.1.2+1.9.4-BETA-1.18
		megane-runtime: megane-runtime 6.1.2
		megane-vanilla: megane-vanilla 6.1.2+1.18.1
		midnightlib: MidnightLib 0.3.1
		milk_plus: Milk+ 1.3.0
		minecraft: Minecraft 1.18.1
		minieffects: Mini Effects 4.0.0
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.0.1
		more-axolotls: More Axolotls 1.0.2
		morebannerfeatures: More Banner Features 1.1.3
		morerespawnanchors: More Respawn Anchors 1.0.3
		morevillagers-fabric: MoreVillagersFabric 3.0.0-SNAPSHOT
		mousetweaks: Mouse Tweaks 2.19
		multipart_entities: MultipartEntities 1.1.4-1.18-rc3
		mushroomorigins: Mushroom Origins 1.1
		mythic-mounts: Mythic Mounts 1.18-4.0
		mythicmetals: Mythic Metals 0.11.0
		netherportalfix: NetherPortalFix 9.0.0
		no-telemetry: No Telemetry 1.3.0
		no_null_processors: No Null Processors - Fabric 2.0.0+1.18
		notes: Notes 1.0.9
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		omega-config: OmegaConfig 1.0.8
		onsoulfire: On Soul Fire 1.18-1
		org_anarres_jcpp: jcpp 1.4.14
		org_apache_commons_commons-text: commons-text 1.9
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		origins: Origins 1.3.1
		owo: oωo 0.3.8+1.18
		oxidized: Oxidized 1.5.1
		paintings: Paintings++ 1.0.0.6
		passable-leaves: Passable Leaves 2.0.1
		patchouli: Patchouli 1.18.1-61-FABRIC
		pehkui: Pehkui 3.0.0+1.14.4-1.18
		pickupnotifier: Pick Up Notifier 3.1.0
		placeholder-api: Placeholder API 1.1.3+1.17.1
		player-data-api: Player Data API 0.1.0+1.18
		playerabilitylib: Pal 1.5.0
		plushies: Plushie Mod 1.1
		pride: Pride Lib 1.1.0+1.17
		puzzleslib: Puzzles Lib 3.1.1
		quartzelv: Quartz Elevator 2.0.1+1.18
		quickshulker: Quick Shulker 1.3.1-1.18
		rad: Reload Audio Driver 1.0.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		realisticfirespread: Realistic Fire Spread 1.18-1
		repurposed_structures: Repurposed Structures 3.1.12+1.18.1
		rocks: This Rocks! 1.5.2
		rotten: FleshZ 1.4.4
		roughlyenoughitems: Roughly Enough Items 7.1.356
		rpgdifficulty: Rpg Difficulty 1.0.7
		salem: Salem 1.1.1
		satin: Satin 1.7.0
		sculk_worm: Sculk Worm 0.1.2
		seasons: Fabric Seasons 1.3-BETA+1.18
		seedfix: Seed Fix 1.0.0
		shulkerboxtooltip: Shulker Box Tooltip 3.0.5+1.18
		shulkerutils: shulkerutils 1.0.4-1.18
		skinlayers: 3d Skin Layers 1.3.1
		soaringstructures2: Soaring Structures 2 1.18 - 2.0
		sodium: Sodium 0.4.0-alpha5+build.9
		sodium-extra: Sodium Extra 0.3.7
		someforgepatchesported: Some Forge Patches Ported 1.0.1
		spruceui: SpruceUI 3.3.0+1.17
		staffofbuilding: Staff of Building 1.4.0-1.18.1
		starlight: Starlight 1.0.0+fabric.d0a3220
		starterkit-fabric: Starter Kit (Fabric) 3.1
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.4.1
		styled-nicknames: Styled Nicknames 1.0.3+1.18
		styledchat: Styled Chat 1.2.2+1.18
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terralith: Terralith for Fabric 2.0_b0.1.8
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.18
		things: Things 0.2.8+1.18
		thonkutil: ThonkUtil 2.2.1+1.18
		thonkutil-base: ThonkUtil Base 1.1.0+d5f23f2ac8
		thonkutil-coords-v1: ThonkUtil Coords (v1) 1.0.1+f101d003c8
		thonkutil-legacy: ThonkUtil Legacy 1.0.2+6fa117f8c8
		thonkutil-potions-v0: ThonkUtil Potions (v0) 1.2.0+e4c51c01c8
		thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.0+769eee82c8
		tinyskeletons: Tiny Skeletons 3.1.0
		toms_storage: Tom's Simple Storage Mod 1.1.19
		tooltipfix: ToolTip Fix 1.0.4-1.18
		tooltiprareness: Tooltip Rareness 1.0.3
		torchbowmod: TorchBowMod 1.0
		towers_of_the_wild_reworked: Towers of the Wild: Reworked 2.1.0
		tradingpost: Trading Post 3.1.2
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.1.0
		tweed4_annotated: tweed4_annotated 1.2.0
		tweed4_base: tweed4_base 1.3.1
		tweed4_data: tweed4_data 1.2.0
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.2
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.2
		twigs: Twigs 1.1.2
		twm: The Wild Mod 0.2
		unvotedandshelved: Unvoted & Shelved 1.0.4
		upgradedshulkers: Upgraded Shulkers 1.1.1-1.18
		urns: Urns 1.0.1
		vanilla_degus: Vanilla Degus 1.3.0
		veinmining: Vein Mining 0.0.11-1.18
		villager-hats: Villager Hats Mod 1.2.1
		villagernames: Villager Names 2.0.2
		villagerquests: Villager Quests 1.0.2
		villagespawnpoint-fabric: Village Spawn Point (Fabric) 1.8
		visuality: Visuality 0.3.3
		visualworkbench: Visual Workbench 3.1.0
		voidtotem: VoidTotem (Fabric) 1.18.1-1.1.0
		wandering_collector: Wandering Collector 1.0.3+mc1.18-rc3
		waystones: Waystones 2.3.5
		windchimes: Windchimes 1.2.0
		wmitaf: WMITAF 2.2.0
		wthit: wthit 4.4.0
		xaerominimap: Xaero's Minimap 21.22.5
		xaeroworldmap: Xaero's World Map 1.18.7
		xlpackets: XLPackets 2.1-1.17.1
		xp_storage: XP Storage 1.4.3+1.18
		xp_storage_trinkets: XP Storage - Trinkets 0.1+1.18
		yigd: You're in Grave Danger 1.2.8B
	XR: Session running
	Runtime Name: SteamVR/OpenXR
	Runtime Version: 0.1.0
	Headset Name: SteamVR/OpenXR : holographic
	Headset Vendor: 10462
	Headset Orientation Tracking: true
	Headset Position Tracking: true
	Headset Max Width: 2568
	Headset Max Height: 2512
	Headset Max Layer Count: 16
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon RX 6700 XT GL version 3.2.14802 Core Profile Forward-Compatible Context 21.12.1 30.0.14011.3017, ATI Technologies Inc.
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/Terralith_2.0_Biome_Name_Fix.zip, file/Skyrim Soundpack v5.8.zip, file/STONEBORN - 1.18 - V3.0.zip, file/Excalibur_V1.18.zip, file/EmbellishedStone-1.18-1.0.0.zip, file/EclecticTrove-1.18-1.0.1.zip
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 5800X 8-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['Silver_Clock'/71, l='ServerLevel[New World]', x=3182.15, y=78.00, z=-470.59]]
	Data Packs: vanilla, Fabric Mods`

**Comment by Sorenon** [comment]
please try again with the latest version of mcxr-core from https://github.com/Sorenon/MCXR/releases/tag/c0.1.1-p0.1.1

**Comment by gbreuil** [comment]
It works now, i just need to find a way to not render on my pc screen the game with shaders (30fps).
Last version of mcxr-core fixed the issue.
