### ISSUE TITLE
Red screen

### ISSUE THREAD

**Issue by Daxelarne** [Sorenon/MCXR#21]
When i start the game from my computer, i end up in a red screen on the oculus, with red everywhere. When i look on the computer the headset is detected.

Oculus Quest 2
Oculus link (cable)
Last version of both MCXR

**Comment by Flamgop** [comment]
That is intended. You need to start the game from your computer or install the Title Worlds mod

**Comment by Sorenon** [comment]
☝️ Yeah what he said
