### ISSUE TITLE
Game running in oculus rift app, instead of steamvr

### ISSUE THREAD

**Issue by DmanMC** [Sorenon/MCXR#23]
the game opens in the rift app and not steamvr, so im not able to modify the controls in steamvr

**Comment by DmanMC** [comment]
also im not very experienced with steamvr, so if im doing something wrong myself let me know

**Comment by DmanMC** [comment]
or is there another way to modify controls by now?

**Comment by Undercoverer** [comment]
Do you have steam set as your openxr runtime?
![Screenshot_20220111-003849-049.png](https://user-images.githubusercontent.com/53386175/148887376-6188f8e1-1edd-4da5-acc5-2950596924f6.png)

**Comment by DmanMC** [comment]
ok, i did that, but now it crashes whenever i start the game

**Comment by DmanMC** [comment]
[latest.log](https://github.com/Sorenon/MCXR/files/7849805/latest.log)

**Comment by Undercoverer** [comment]
LambdaControls is for 1.17

**Comment by Sorenon** [comment]
This looks like a conflict between LambdaControls and Titleworlds. 

You shouldn't need LambdaControls installed anyway as MCXR overwrites some of its functionality.
