### ISSUE TITLE
Keep on getting this error when launching the game 

### ISSUE THREAD

**Issue by NotFam** [Sorenon/MCXR#26]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod '[MCXR] Core' (mcxr-core) 0.1.1 requires any version of fabric, which is missing!
	 - Mod '[MCXR] Play' (mcxr-play) 0.1.1 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Fishvap** [comment]
Did you install Fabric Loader? Why did you reopen and close this multiple times?

**Comment by Flamgop** [comment]
They're missing fabric api.

**Comment by Fishvap** [comment]
yep, I meant Fabric API, I goofed

**Comment by NotFam** [comment]
Found it out 10 minutes after posting this issue
