### ISSUE TITLE
Other Methods of Locomotion

### ISSUE THREAD

**Issue by paperclone22** [Sorenon/MCXR#27]
Are there plans for configurable modes of locomotion? Currently movement seems to be based on head orientation. This method usually makes me sick after a few minutes.

Movement based on hand orientation or teleport would greatly improve my experience.

Apologies if these already exist, I checked for a config file but didn't find one

**Comment by Mage-Enderman** [comment]
I agree more locomotion options would be fantastic! (Like smooth turning!)

**Comment by LoganDark** [comment]
> (Like smooth turning!)

Wait, this mod doesn't already have smooth turning?! Thanks for the warning.

**Comment by Sorenon** [comment]
Smooth turning and different movement directions have both been added, teleportion will be released soon.
