### ISSUE TITLE
Sneaking does not reduce movement speed

### ISSUE THREAD

**Issue by Tomatobird8** [Sorenon/MCXR#43]
Player now moves at full speed while sneaking.
c0.2.1-p0.2.1

**Comment by Flamgop** [comment]
I believe this should've been fixed with [this pull request](https://github.com/Sorenon/MCXR/pull/35#issue-1157672758)

**Comment by Tomatobird8** [comment]
> I believe this should've been fixed with [this pull request](https://github.com/Sorenon/MCXR/pull/35#issue-1157672758)

Correct, that pr did fix it however recent changes have unfortunately broken it again.

**Comment by ManiacGamer156** [comment]
Yeah, looks like Sorenon removed the piece of code that made it work, i’ll open a new pull request soon

**Comment by ManiacGamer156** [comment]
I have opened the PR, #44

**Comment by Tomatobird8** [comment]
Fixed in 794129557147697bae22b5322a2df56e99026966
