### ISSUE TITLE
XR method returned - 51

### ISSUE THREAD

**Issue by nav2727** [Sorenon/MCXR#54]

**Comment by Flamgop** [comment]
logs?

**Comment by nav2727** [comment]
[latest.log](https://github.com/Sorenon/MCXR/files/8566963/latest.log)

**Comment by nav2727** [comment]
> logs?

[latest.log](https://github.com/Sorenon/MCXR/files/8567023/latest.log)

**Comment by Sorenon** [comment]
You don't have an OpenXR runtime setup somehow? Depending on your headset you will want to go into SteamVR or Oculus and find the 'set as default OpenXR runtime' button.

**Comment by nav2727** [comment]
I already set up openxr oculus as default

**Comment by nav2727** [comment]
![image](https://user-images.githubusercontent.com/86252431/165414787-d2b76c41-0157-4685-986f-188a40d80f32.png)

**Comment by Sorenon** [comment]
You could try setting SteamVR as the active runtime. Maybe Oculus set the path incorrectly?

**Comment by nav2727** [comment]
it works but the thing is I don't use steam VR because it doesn't run well on my Hardware
