### ISSUE TITLE
Crash of the game at startup.

### ISSUE THREAD

**Issue by Lolothepro** [Sorenon/MCXR#79]
[crash-2022-06-18_08.31.37-client.txt](https://github.com/Sorenon/MCXR/files/8933075/crash-2022-06-18_08.31.37-client.txt)

**Comment by Sorenon** [comment]
you need to install the OpenXR loader for your distro

**Comment by Lolothepro** [comment]
I have the libopenxr-loader1 package (https://packages.ubuntu.com/fr/jammy/amd64/libopenxr-loader1/filelist)

**Comment by Lolothepro** [comment]
uninstalling and reinstalling the package solves the issue.
