### ISSUE TITLE
Use with keyboard

### ISSUE THREAD

**Issue by Constructor-999** [Sorenon/MCXR#87]
Hello.
I don't have controllers and I wanted to know if we could play it with the keyboard and the mouse,
 tanks

**Comment by FedFer98123** [comment]
Short Answer: No.

Long Answer: You can install the non-vr installation using only [mcxr-core](https://modrinth.com/mod/mcxr-core), this currently doesn't change anything in a non-vr environment but there's currently in development a feature that will allow non-vr players to see vr players model (see their arms moving)

**Comment by Sorenon** [comment]
Issue seems to duplicate #53
