### ISSUE TITLE
[iris-fix branch] Reloading resource packs causes projection matrix issues

### ISSUE THREAD

**Issue by xanthousm** [Sorenon/MCXR#88]
Running the iris-fix branch, if you add or remove a resource pack, the projection matrix used for translucent blocks, entities, and the UI becomes offset from where it should be, leading to the affected blocks/entities appearing warped and cut-off. This happens with iris installed even when shaders are disabled. 
Examples below are:
- newly opened menu, hands, and pointer positioned in front of player, appears warped in bottom corner. Clouds also warped
- water blocks warped (should be at neck height, parallel to ground)
- warped UI and nether portal, showing a section being cut off
![VirtualDesktop Android-20220719-204209](https://user-images.githubusercontent.com/70198941/179733095-11b246ca-199d-4fc0-afd4-df16c2f4f5e4.jpg)
![VirtualDesktop Android-20220719-204223](https://user-images.githubusercontent.com/70198941/179733107-4b40c59e-efc5-4980-a1d7-91a95ce86dce.jpg)
![VirtualDesktop Android-20220719-204205](https://user-images.githubusercontent.com/70198941/179733110-366d38e7-38b6-411b-9014-6832c436d6fa.jpg)

**Comment by Sorenon** [comment]
woot woot
